# Generated by Django 3.0.6 on 2020-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20200603_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reacted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
