# Generated by Django 3.0.6 on 2020-06-03 21:35

from django.db import migrations

DEFAULT_PUSH_TXT = """{{ msg }}

Viele Grüße
Dein Team von naklar.io

-----------------------

Du erhältst diese Nachricht, da du Benachrichtigungen auf naklar.io aktiviert hast.
"""
DEFAULT_PUSH_HTML = """{{ msg }}
<br>
<br>
<p>
Viele Grüße<br>
Dein Team von naklar.io<br>
<br>
<hr>
<br>
Du erhältst diese Nachricht, da du Benachrichtigungen auf naklar.io aktiviert hast.
</p>
"""

def create_template(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    if not EmailTemplate.objects.filter(name='notification').exists():
        EmailTemplate.objects.create(
            name='notification', content=DEFAULT_PUSH_TXT, html_content=DEFAULT_PUSH_HTML, subject="naklar.io - {{ subject }}", description="Standard-Template für PUSH-Notifications")


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20200603_1926'),
        ('post_office', '0008_attachment_headers')
    ]

    operations = [
        migrations.RunPython(create_template)
    ]
