# Generated by Django 3.1.4 on 2020-12-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_auto_20200603_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='enable_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='ranges_mode',
            field=models.CharField(choices=[('ALLOW', 'Während dieser Zeiten erlauben'), ('BLOCK', 'Während dieser Zeiten verbieten')], default='BLOCK', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.notification')),
            ],
        ),
    ]
