# Generated by Django 3.1.3 on 2020-12-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scheduling.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_auto_20201114_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[scheduling.validators.validate_start_time])),
                ('duration', models.DurationField()),
                ('weekly', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[scheduling.validators.validate_start_time])),
                ('duration', models.DurationField(validators=[scheduling.validators.validate_duration])),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subject')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('timeslot', 'start_time'), name='unique_appointment_timeslot_start_time'),
        ),
    ]
