# Generated by Django 3.1.4 on 2021-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
