# Generated by Django 3.1.4 on 2020-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_timeslot_start_time',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'OWNER_REJECTED'), ('status', 'INVITEE_REJECTED'), _connector='OR'), _negated=True), fields=('timeslot', 'start_time'), name='unique_appointment_timeslot_start_time'),
        ),
    ]
