# Generated by Django 3.1.3 on 2020-12-09 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('roulette', '0001_initial'), ('roulette', '0002_feedback'), ('roulette', '0003_meeting_match'), ('roulette', '0004_auto_20200402_2006'), ('roulette', '0005_auto_20200402_2010'), ('roulette', '0006_auto_20200408_1342'), ('roulette', '0007_feedback_meeting'), ('roulette', '0008_auto_20200408_1352'), ('roulette', '0009_auto_20200408_1912'), ('roulette', '0010_meeting_is_establishing'), ('roulette', '0011_auto_20200416_1253')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('failed_matches', models.ManyToManyField(blank=True, related_name='_tutorrequest_failed_matches_+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('is_manual_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('failed_matches', models.ManyToManyField(blank=True, related_name='_studentrequest_failed_matches_+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('is_manual_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_agree', models.BooleanField(default=False)),
                ('tutor_agree', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('changed_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roulette.studentrequest')),
                ('tutor_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roulette.tutorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Meeting-Name')),
                ('attendee_pw', models.CharField(max_length=120, null=True)),
                ('moderator_pw', models.CharField(max_length=120, null=True)),
                ('established', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('time_established', models.DateTimeField(blank=True, null=True, verbose_name='Aufgebaut')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.match', to_field='uuid')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_meetings', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('time_ended', models.DateTimeField(blank=True, null=True, verbose_name='Beendet')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_meetings', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('is_establishing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Nachricht')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_feedback', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.meeting')),
            ],
            options={
                'unique_together': {('receiver', 'provider', 'meeting')},
            },
        ),
    ]
