# Generated by Django 3.0.4 on 2020-04-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_auto_20200402_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.Match', to_field='uuid'),
        ),
    ]
