# Generated by Django 3.0.5 on 2020-04-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_auto_20200408_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.Meeting'),
        ),
    ]
