# Generated by Django 3.0.5 on 2020-04-08 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulette', '0007_feedback_meeting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('receiver', 'provider', 'meeting')},
        ),
    ]
