# Generated by Django 3.0.5 on 2020-04-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_auto_20200408_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.Match', to_field='uuid'),
        ),
    ]
