# Generated by Django 3.0.5 on 2020-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_auto_20200408_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_establishing',
            field=models.BooleanField(default=False),
        ),
    ]
