# Generated by Django 3.0.5 on 2020-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0010_meeting_is_establishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='is_manual_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='is_manual_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
