# Generated by Django 3.0.5 on 2020-04-16 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('roulette', '0012_auto_20200416_1430'), ('roulette', '0013_auto_20200416_1444'), ('roulette', '0014_auto_20200416_1447'), ('roulette', '0015_auto_20200416_1454'), ('roulette', '0016_auto_20200416_1504')]

    dependencies = [
        ('roulette', '0011_auto_20200416_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='last_poll',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='last_poll',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
