# Generated by Django 3.0.6 on 2020-05-19 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulette', '0014_report_squashed_0015_auto_20200430_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='deactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='deactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
    ]
