# Generated by Django 3.1.3 on 2020-12-09 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('roulette', '0015_auto_20200519_1132'), ('roulette', '0016_auto_20200523_1141'), ('roulette', '0017_auto_20200624_1305'), ('roulette', '0018_auto_20200624_1536')]

    dependencies = [
        ('roulette', '0014_report_squashed_0015_auto_20200430_1018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='deactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='deactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='meeting',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roulette.meeting'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='meeting',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roulette.meeting'),
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-time_established']},
        ),
        migrations.AddField(
            model_name='match',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_match', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tutor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_match', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.match', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.studentrequest'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tutor_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.tutorrequest'),
        ),
    ]
