# Generated by Django 3.0.7 on 2020-06-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0017_auto_20200624_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='student_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.StudentRequest'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tutor_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.TutorRequest'),
        ),
    ]
