# Generated by Django 3.0.10 on 2020-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('roulette', '0019_auto_20200910_1259'), ('roulette', '0020_auto_20200910_1505')]

    dependencies = [
        ('roulette', '0018_auto_20200624_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='connected_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='connected_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
