# Generated by Django 3.0.10 on 2020-10-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0019_auto_20200910_1259_squashed_0020_auto_20200910_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fail_reason',
            field=models.CharField(choices=[('TR', 'Tutor reject'), ('TT', 'Tutor timeout'), ('SR', 'Student reject'), ('ST', 'Student timeout'), ('BT', 'Both timed out'), ('OR', 'Other reason')], default='OR', max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.StudentRequest'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tutor_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roulette.TutorRequest'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(failed=False), fields=('student_request', 'tutor_request'), name='unique_active_match_per_request'),
        ),
    ]
