# Generated by Django 3.0.10 on 2020-10-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0021_auto_20201028_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
