# Generated by Django 3.1.3 on 2020-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0023_auto_20201029_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fail_reason',
            field=models.CharField(choices=[('TR', 'Tutor reject'), ('TT', 'Tutor timeout'), ('TD', 'Tutor disconnect'), ('SR', 'Student reject'), ('ST', 'Student timeout'), ('SD', 'Student disconnect'), ('BT', 'Both timed out'), ('OR', 'Other reason')], default='OR', max_length=2),
        ),
    ]
