# Generated by Django 3.1.3 on 2020-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0025_auto_20201117_1640'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_active_match_per_tutor',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_active_match_per_student',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('failed', False), ('successful', False)), fields=('student_request',), name='unique_active_match_per_student'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('failed', False), ('successful', False)), fields=('tutor_request',), name='unique_active_match_per_tutor'),
        ),
    ]
