# Generated by Django 3.1.3 on 2020-12-09 15:05

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('account', '0001_initial'), ('account', '0002_auto_20200407_1242'), ('account', '0003_auto_20200407_1718'), ('account', '0004_tutordata_profile_picture'), ('account', '0005_auto_20200409_1113'), ('account', '0006_auto_20200413_1438'), ('account', '0007_auto_20200413_1447'), ('account', '0008_passwordresettoken'), ('account', '0009_auto_20200413_1655'), ('account', '0010_trackingdenycounter'), ('account', '0011_auto_20201114_1926')]

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name des Schultyps')),
            ],
            options={
                'verbose_name': 'Schultyp',
                'verbose_name_plural': 'Schultypen',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('shortcode', models.CharField(max_length=2, verbose_name='Kurzbezeichnung')),
            ],
            options={
                'verbose_name': 'Bundesland',
                'verbose_name_plural': 'Bundesländer',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Klasse')),
                ('school_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.schooltype')),
            ],
            options={
                'verbose_name': 'Schultyp- und Klassenkombination',
                'verbose_name_plural': 'Schultyp- und Klassenkombinationen',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Beitritt')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.state', verbose_name='Bundesland')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('gender', models.CharField(choices=[('MA', 'männlich'), ('FE', 'weiblich'), ('DI', 'divers')], default='', max_length=2, verbose_name='Geschlecht')),
                ('email_verified', models.BooleanField(default=False, verbose_name='E-Mail bestätigt')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Nutzer',
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.schooldata', verbose_name='Klasse und Schulart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schülerdaten',
                'verbose_name_plural': 'Schülerdaten',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail Verifizierungstoken',
                'verbose_name_plural': 'E-Mail Verifizierungstoken',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooldata', models.ManyToManyField(to='account.SchoolData', verbose_name='Mögliche Schultypen/Klassenstufen')),
                ('subjects', models.ManyToManyField(to='account.Subject', verbose_name='Fächer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification_file', models.FileField(blank=True, null=True, upload_to=account.models.tutor_upload_path, verbose_name='Vefizierungsdatei')),
                ('verified', models.BooleanField(default=False, verbose_name='Verifiziert')),
                ('profile_picture', models.ImageField(null=True, upload_to=account.models.profile_upload_path, verbose_name='Profilbild')),
            ],
            options={
                'verbose_name': 'Tutordaten',
                'verbose_name_plural': 'Tutordaten',
            },
        ),
        migrations.CreateModel(
            name='TrackingDenyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
