# Generated by Django 3.1.4 on 2020-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial_squashed_0011_auto_20201114_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MA', 'männlich'), ('FE', 'weiblich'), ('DI', 'divers')], max_length=2, verbose_name='Geschlecht'),
        ),
    ]
