# Generated by Django 3.1.4 on 2020-12-21 16:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201212_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.subject_upload_path),
        ),
    ]
