# Generated by Django 3.1.4 on 2020-12-29 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('account', '0004_accesscode'), ('account', '0005_accesscode_redeem_time'), ('account', '0006_auto_20201228_1902')]

    dependencies = [
        ('account', '0003_subject_img'),
        ('roulette', '0020_auto_20201028_1411_squashed_0026_auto_20201117_1643'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('redeem_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
