# Generated by Django 3.0.5 on 2020-04-08 15:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200407_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordata',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=account.models.profile_upload_path, verbose_name='Profilbild'),
        ),
    ]
