# Generated by Django 3.0.5 on 2020-04-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200409_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Nutzer', 'verbose_name_plural': 'Nutzer'},
        ),
        migrations.AlterModelOptions(
            name='schooldata',
            options={'verbose_name': 'Schultyp- und Klassenkombination', 'verbose_name_plural': 'Schultyp- und Klassenkombinationen'},
        ),
        migrations.AlterModelOptions(
            name='schooltype',
            options={'verbose_name': 'Schultyp', 'verbose_name_plural': 'Schultypen'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Bundesland', 'verbose_name_plural': 'Bundesländer'},
        ),
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'Schülerdaten', 'verbose_name_plural': 'Schülerdaten'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='tutordata',
            options={'verbose_name': 'Tutordaten', 'verbose_name_plural': 'Tutordaten'},
        ),
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'verbose_name': 'E-Mail Verifizierungstoken', 'verbose_name_plural': 'E-Mail Verifizierungstoken'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.State', verbose_name='Bundesland'),
        ),
    ]
