# Generated by Django 3.0.4 on 2020-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('recv_updates', models.BooleanField(default=False)),
                ('ind_type', models.CharField(choices=[('TU', 'Tutor'), ('PA', 'Eltern'), ('ST', 'Schüler')], max_length=2)),
            ],
        ),
    ]
